/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 25, 2018 at 11:20:38 PM Eastern European Standard Time
* Operating System: Version 11.1.2 (Build 15B202)
* Image Source: /System/Library/Frameworks/Foundation.framework/Foundation
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Foundation/_NSLayoutRuleNode.h>

@class NSLayoutConstraint;

@interface _NSConstraintDescriptionLayoutRuleNode : _NSLayoutRuleNode {

	NSLayoutConstraint* _ownedConstraint;

}

@property (retain) NSLayoutConstraint * ownedConstraint;              //@synthesize ownedConstraint=_ownedConstraint - In the implementation block
-(NSLayoutConstraint *)ownedConstraint;
-(void)setOwnedConstraint:(NSLayoutConstraint *)arg1 ;
-(void)dealloc;
@end

