/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 25, 2018 at 11:20:38 PM Eastern European Standard Time
* Operating System: Version 11.1.2 (Build 15B202)
* Image Source: /System/Library/Frameworks/Foundation.framework/Foundation
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

@class NSArray;


@protocol _NSLayoutRuleNodeParent <NSObject>
@property (copy,readonly) NSArray * _childRuleNodes; 
@required
-(void)_addChildRuleNode:(id)arg1;
-(void)_removeChildRuleNode:(id)arg1;
-(NSArray *)_childRuleNodes;

@end

