/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 25, 2018 at 11:20:40 PM Eastern European Standard Time
* Operating System: Version 11.1.2 (Build 15B202)
* Image Source: /System/Library/Frameworks/Foundation.framework/Foundation
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

//#import <libobjc.A.dylib/NSCoding.h>
#import <Foundation/Foundation.h>

@protocol NSISVariableDelegate;
@class NSISEngine, NSMutableSet;

@interface NSISVariable : NSObject <NSCoding> {

	id<NSISVariableDelegate> _delegate;
	unsigned _ident;
	NSISEngine* _crossIndexEngine;
	NSMutableSet* _crossIndexSet;

}
@property (assign) NSMutableSet* crossIndexSet;
@property (assign) id<NSISVariableDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (readonly) BOOL shouldBeMinimized; 
@property (readonly) int valueRestriction; 
+(id)variableWithName:(id)arg1 valueRestriction:(int)arg2 shouldBeMinimized:(BOOL)arg3 valueIsUserObservable:(BOOL)arg4 ;
+(id)variableWithName:(id)arg1 valueRestriction:(int)arg2 shouldBeMinimized:(BOOL)arg3 ;
+(id)variableMarkingConstraint:(id)arg1 valueRestriction:(int)arg2 shouldBeMinimized:(BOOL)arg3 ;
+(id)variableWithDelegate:(id)arg1 valueRestriction:(int)arg2 shouldBeMinimized:(BOOL)arg3 ;
-(id)markedConstraint;
-(int)valueRestriction;
-(BOOL)markedConstraintIsEligibleForIntegralizationAdjustment;
-(double)allowedMagnitudeForIntegralizationAdjustmentOfMarkedConstraint;
-(BOOL)shouldBeIntegral;
-(BOOL)valueIsUserVisible;
-(BOOL)shouldBeMinimized;
-(id)init;
-(id<NSISVariableDelegate>)delegate;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(void)setDelegate:(id<NSISVariableDelegate>)arg1 ;
-(unsigned long long)hash;
-(id)description;
@end

