/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 25, 2018 at 11:20:40 PM Eastern European Standard Time
* Operating System: Version 11.1.2 (Build 15B202)
* Image Source: /System/Library/Frameworks/Foundation.framework/Foundation
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Foundation/Foundation-Structs.h>
#import <libobjc.A.dylib/NSISRowBody.h>

@class NSMutableArray, NSString;

@interface NSISObjectiveLinearExpression : NSObject <NSISRowBody> {

	CFDictionaryRef _priorityMap;
	NSMutableArray* _variablesSortedByPriorityVectors;
	CFDataRef _constant;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(unsigned long long)variableCount;
-(void)verifyInternalIntegrity;
-(void)removeVariable:(id)arg1 ;
-(void)addVariable:(id)arg1 priority:(double)arg2 times:(double)arg3 processVariableNewToReceiver:(/*^block*/id)arg4 processVariableDroppedFromReceiver:(/*^block*/id)arg5 ;
-(void)addExpression:(id)arg1 priority:(double)arg2 times:(double)arg3 processVariableNewToReceiver:(/*^block*/id)arg4 processVariableDroppedFromReceiver:(/*^block*/id)arg5 ;
-(void)replaceVariable:(id)arg1 withVariablePlusDelta:(double)arg2 timesVariable:(id)arg3 processVariableNewToReceiver:(/*^block*/id)arg4 processVariableDroppedFromReceiver:(/*^block*/id)arg5 ;
-(void)enumerateVariables:(/*^block*/id)arg1 ;
-(void)leadingPriority:(double*)arg1 andValue:(double*)arg2 forVariable:(id)arg3 ;
-(id)initWithLinearExpression:(id)arg1 priority:(double)arg2 ;
-(BOOL)constantTermIsZero;
-(void)replaceVariable:(id)arg1 withVariablePlusDelta:(double)arg2 ;
-(void)replaceVariable:(id)arg1 withExpression:(id)arg2 processVariableNewToReceiver:(/*^block*/id)arg3 processVariableDroppedFromReceiver:(/*^block*/id)arg4 ;
-(void)addVariable:(id)arg1 priority:(double)arg2 times:(double)arg3 ;
-(void)incrementConstantWithPriority:(double)arg1 value:(double)arg2 ;
-(CFDataRef)priorityVectorForVariable:(id)arg1 ;
-(void)setPriorityVector:(CFDataRef)arg1 forKnownAbsentVariable:(id)arg2 ;
-(void)incrementConstantWithPriorityVector:(CFDataRef)arg1 timesScalarCoefficient:(double)arg2 ;
-(id)restrictedVariableWithCoefficientOfLargestNegativeMagnitude;
-(id)init;
-(void)dealloc;
-(NSString *)description;
@end

