/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 25, 2018 at 11:20:40 PM Eastern European Standard Time
* Operating System: Version 11.1.2 (Build 15B202)
* Image Source: /System/Library/Frameworks/Foundation.framework/Foundation
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Foundation/Foundation.h>
#import "NSISConstraint.h"

@class _NSConstraintDescriptionLayoutRuleNode, NSLayoutAnchor, NSString, NSSet;

@interface NSLayoutConstraint() {

	id _container;
	id _firstAnchor;
	id _secondAnchor;
	double _constant;
	double _loweredConstant;
	id _markerAndPositiveExtraVar;
	id _negativeExtraVar;
	unsigned long long _layoutConstraintFlags;
	float _coefficient;
	float _priority;

}

@property (setter=_setAssociatedRuleNode:) _NSConstraintDescriptionLayoutRuleNode * _associatedRuleNode; 
@property (setter=_setFirstAnchor:,copy) NSLayoutAnchor * firstAnchor;                                                                               //@synthesize firstAnchor=_firstAnchor - In the implementation block
//@property (setter=_setRelation:) long long relation;
//@property (setter=_setMultiplier:) double multiplier;
//@property (setter=_setSecondAnchor:,copy) NSLayoutAnchor * secondAnchor;                                                                             //@synthesize secondAnchor=_secondAnchor - In the implementation block
@property (copy) NSString * identifier;
@property (readonly) BOOL hasBeenLowered; 
@property (assign) id container; 
@property (setter=_setContainerDeclaredConstraint:) BOOL _containerDeclaredConstraint; 
@property (readonly) double unsatisfaction; 
@property (copy) NSString * symbolicConstant; 
@property (assign,setter=_setLoweredConstantNeedsUpdate:,getter=_loweredConstantNeedsUpdate,nonatomic) BOOL loweredConstantNeedsUpdate; 
@property (copy,readonly) NSSet * _referencedLayoutItems; 
//@property (assign) float priority;
//@property (assign) BOOL shouldBeArchived;
//@property (readonly) id firstItem;
//@property (readonly) long long firstAttribute;
//@property (readonly) id secondItem;
//@property (readonly) long long secondAttribute;
//@property (assign) double constant;
//@property (getter=isActive) BOOL active;
//@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)_findCommonAncestorOfItem:(id)arg1 andItem:(id)arg2 ;
+(void)_addOrRemoveConstraints:(id)arg1 activate:(BOOL)arg2 ;
+(void)_setLegacyDecodingOnly:(BOOL)arg1 ;
+(id)constraintWithItem:(id)arg1 attribute:(long long)arg2 relatedBy:(long long)arg3 toItem:(id)arg4 attribute:(long long)arg5 multiplier:(double)arg6 symbolicConstant:(id)arg7 theme:(id)arg8 ;
+(id)constraintWithAnchor:(id)arg1 relatedBy:(long long)arg2 constant:(double)arg3 ;
//+(id)constraintWithItem:(id)arg1 attribute:(long long)arg2 relatedBy:(long long)arg3 toItem:(id)arg4 attribute:(long long)arg5 multiplier:(double)arg6 constant:(double)arg7 ;
//+(void)activateConstraints:(id)arg1 ;
//+(id)constraintsWithVisualFormat:(id)arg1 options:(unsigned long long)arg2 metrics:(id)arg3 views:(id)arg4 ;
//+(void)deactivateConstraints:(id)arg1 ;
+(id)constraintWithItem:(id)arg1 attribute:(long long)arg2 relatedBy:(long long)arg3 toItem:(id)arg4 attribute:(long long)arg5 ;
+(id)constraintWithItem:(id)arg1 attribute:(long long)arg2 relatedBy:(long long)arg3 constant:(double)arg4 ;
+(id)constraintWithItem:(id)arg1 attribute:(long long)arg2 relatedBy:(long long)arg3 toItem:(id)arg4 attribute:(long long)arg5 multiplier:(double)arg6 symbolicConstant:(id)arg7 ;
+(id)constraintWithItem:(id)arg1 attribute:(long long)arg2 relatedBy:(long long)arg3 toItem:(id)arg4 attribute:(long long)arg5 constant:(double)arg6 ;
+(id)constraintWithItem:(id)arg1 attribute:(long long)arg2 relatedBy:(long long)arg3 toItem:(id)arg4 attribute:(long long)arg5 multiplier:(double)arg6 ;
+(id)constraintWithAnchor:(id)arg1 relatedBy:(long long)arg2 toAnchor:(id)arg3 multiplier:(double)arg4 constant:(double)arg5 ;
-(NSSet *)_referencedLayoutItems;
-(id)equationDescription;
-(NSLayoutAnchor *)secondAnchor;
-(_NSConstraintDescriptionLayoutRuleNode *)_associatedRuleNode;
-(void)_setAssociatedRuleNode:(id)arg1 ;
-(void)_setContainerDeclaredConstraint:(BOOL)arg1 ;
-(id)_ancestorRuleNodes;
-(id)sourceRuleHierarchy;
-(unsigned long long)_constraintValueHashIncludingConstant:(BOOL)arg1 includeOtherMutableProperties:(BOOL)arg2 ;
-(BOOL)_isEqualToConstraintValue:(id)arg1 includingConstant:(BOOL)arg2 includeOtherMutableProperties:(BOOL)arg3 ;
-(id)_constraintValueCopy;
-(void)_setMutablePropertiesFromConstraint:(id)arg1 ;
-(double)nsis_allowedMagnitudeForIntegralizationAdjustmentOfConstraintWithMarker:(id)arg1 ;
-(double)unsatisfaction;
-(id)_negativeExtraVar;
-(void)_setFirstAnchor:(id)arg1 ;
-(void)_setSecondAnchor:(id)arg1 ;
-(id)_constantDescriptionForDTrace;
-(double)_allowedMagnitudeForIntegralizationAdjustment;
-(CGSize)_engineToContainerScalingCoefficients;
-(void)setHasBeenLowered:(BOOL)arg1 ;
-(BOOL)_lowerIntoExpression:(id)arg1 reportingConstantIsRounded:(BOOL*)arg2 ;
-(BOOL)_addLoweredExpression:(id)arg1 toEngine:(id)arg2 integralizationAdjustment:(double)arg3 lastLoweredConstantWasRounded:(BOOL)arg4 mutuallyExclusiveConstraints:(id*)arg5 ;
-(double)_allowedMagnitudeForIntegralizationAdjustmentOfConstraintWithMarkerScaling:(double*)arg1 ;
-(id)_symbolicConstant;
-(void)_ensureValueMaintainsArbitraryLimit:(double*)arg1 ;
-(void)_setSymbolicConstant:(id)arg1 ;
-(BOOL)_tryToChangeContainerGeometryWithUndoHandler:(/*^block*/id)arg1 ;
-(BOOL)_effectiveConstant:(double*)arg1 error:(id*)arg2 ;
-(void)_setSymbolicConstant:(id)arg1 constant:(double)arg2 ;
-(id)_descriptionforSymbolicConstant;
-(id)asciiArtDescription;
-(id)_priorityDescription;
-(id)_constraintByReplacingItem:(id)arg1 withItem:(id)arg2 ;
-(void)_setRelation:(long long)arg1 ;
-(double)priorityForVariable:(id)arg1 ;
-(id)_deallocSafeDescription;
-(void)_makeExtraVars;
-(void)_setActive:(BOOL)arg1 mutuallyExclusiveConstraints:(id*)arg2 ;
-(void)_tryToActivateMeasuringUnsatisfactionChanges:(id*)arg1 andMutuallyExclusiveConstraints:(id*)arg2 ;
-(void)_forceSatisfactionMeasuringUnsatisfactionChanges:(id*)arg1 andMutuallyExclusiveConstraints:(id*)arg2 ;
-(BOOL)_nsib_isRedundantInEngine:(id)arg1 ;
-(void)_setFirstItem:(id)arg1 attribute:(long long)arg2 ;
-(void)_setSecondItem:(id)arg1 attribute:(long long)arg2 ;
-(double)dissatisfaction;
-(void)_setLoweredConstantNeedsUpdate:(BOOL)arg1 ;
-(BOOL)_loweredConstantNeedsUpdate;
-(BOOL)_isIBPrototypingLayoutConstraint;
-(BOOL)_existsInEngine:(id)arg1 ;
-(BOOL)_isFudgeable;
-(double)_fudgeIncrement;
-(void)_setMarkerAndPositiveErrorVar:(id)arg1 ;
-(void)_setNegativeExtraVar:(id)arg1 ;
-(BOOL)_deferDTraceLogging;
-(void)_setDeferDTraceLogging:(BOOL)arg1 ;
-(int)_primitiveConstraintType;
-(void)_setPrimitiveConstraintType:(int)arg1 ;
-(id)_allocationDescription;
-(void)_clearWeakContainerReference;
-(BOOL)_containerDeclaredConstraint;
-(id)_constraintByReplacingView:(id)arg1 withView:(id)arg2 ;
-(BOOL)_describesSameRestrictionAsConstraint:(id)arg1 ;
-(id)_loweredExpression;
-(id)_explainUnsatisfaction;
-(id)init;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(void)dealloc;
-(NSString *)description;
-(BOOL)isActive;
-(NSString *)identifier;
-(void)setIdentifier:(NSString *)arg1 ;
-(id)container;
-(void)setActive:(BOOL)arg1 ;
-(void)setPriority:(float)arg1 ;
//-(void)setConstant:(double)arg1 ;
-(void)setAnimations:(id)arg1 ;
-(id)_layoutEngine;
-(void)_removeFromEngine:(id)arg1 ;
-(BOOL)hasBeenLowered;
-(void)_containerGeometryDidChange;
-(float)priority;
-(void)_addToEngine:(id)arg1 ;
-(void)nsis_valueOfVariable:(id)arg1 didChangeInEngine:(id)arg2 ;
-(BOOL)shouldBeArchived;
-(void)setContainer:(id)arg1 ;
//-(long long)firstAttribute;
-(id)firstItem;
-(id)secondItem;
//-(long long)secondAttribute;
//-(double)constant;
//-(void)setShouldBeArchived:(BOOL)arg1 ;
//-(long long)relation;
-(id)animations;
-(void)_setMultiplier:(double)arg1 ;
//-(double)multiplier;
-(NSString *)symbolicConstant;
-(BOOL)_nsib_isRedundant;
-(BOOL)_addToEngine:(id)arg1 integralizationAdjustment:(double)arg2 mutuallyExclusiveConstraints:(id*)arg3 ;
-(BOOL)_loweredConstantIsRounded;
-(id)nsis_descriptionOfVariable:(id)arg1 ;
-(BOOL)nsis_shouldIntegralizeVariable:(id)arg1 ;
-(BOOL)nsis_valueOfVariableIsUserObservable:(id)arg1 ;
-(id)_markerAndPositiveExtraVar;
-(void)setSymbolicConstant:(NSString *)arg1 ;
-(int)_constraintType;
-(BOOL)_referencesLayoutItem:(id)arg1 ;
-(id)_identifier;
-(void)_setIdentifier:(id)arg1 ;
-(id)descriptionAccessory;
-(NSLayoutAnchor *)firstAnchor;
@end

