/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 25, 2018 at 11:22:27 PM Eastern European Standard Time
* Operating System: Version 11.1.2 (Build 15B202)
* Image Source: /System/Library/Frameworks/UIKit.framework/UIKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol NSObservable <NSObject>
@optional
-(id)addObserver:(id)arg1;
-(void)receiveObservedValue:(id)arg1;
-(void)receiveObservedError:(id)arg1;
-(void)finishObserving;
-(void)removeObservation:(id)arg1;

@end

